import type { Metadata } from "next";
import ThemeRegistry from "./theme/ThemeRegistry"; 
import "./global.css";
export const metadata: Metadata = {
  title: "Kingdom-Catering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
