import type { Metadata } from "next";
import ThemeRegistry from "./theme/ThemeRegistry";
import { CssBaseline } from "@mui/material";
import { GlobalStyles } from "./styled-global";

export const metadata: Metadata = {
  title: "Kingdom-Catering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ThemeRegistry>
          <GlobalStyles />
          {children}
          </ThemeRegistry>
      </body>
    </html>
  );
}
